language: swift
xcode_project: ThunderCloud.xcodeproj # path to your xcodeproj folder
osx_image: xcode10.2
cache:
  directories:
  - Carthage
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
matrix:
  include:
    - xcode_scheme: ThunderCloud
      xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone XS Max
before_install:
  - brew install carthage || true
  - brew outdated carthage || brew upgrade carthage
  - gem install xcpretty-travis-formatter --no-rdoc --no-ri --no-document --quiet
before_script:
  # bootstrap the dependencies for the project
  - carthage bootstrap --platform iOS --cache-builds