language: swift
xcode_project: ThunderCloud.xcodeproj # path to your xcodeproj folder
osx_image: xcode13
cache:
  directories:
  - Carthage
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
matrix:
  include:
    - xcode_scheme: ThunderCloud
      xcode_destination: platform=iOS Simulator,OS=15.0,name=iPhone 13
before_install:
  - brew install carthage || true
  - brew outdated carthage || brew upgrade carthage
before_script:
  # bootstrap the dependencies for the project
  - sh quickInstall.sh
